---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: check-merge-conflict
      - id: check-yaml
      - id: end-of-file-fixer
      - id: detect-private-key
      # - id: detect-aws-credentials
      - id: trailing-whitespace
  # - repo: https://github.com/shellcheck-py/shellcheck-py
  #   rev: v0.7.2.1
  #   hooks:
  #     - id: shellcheck
  - repo: https://github.com/IamTheFij/docker-pre-commit
    rev: v2.1.0
    hooks:
      - id: docker-compose-check
      # - id: hadolint
  - repo: https://github.com/hadolint/hadolint
    rev: v2.10.0
    hooks:
      - id: hadolint
  # - repo: https://github.com/Lucas-C/pre-commit-hooks-go
  #   rev: v1.0.1
  #   hooks:
  #   -   id: checkmake
